version: '3.3'

volumes:
  static_volume:

services:
  nginx:
    build: ./nginx
    restart: always
    links:
      - core
    volumes:
      - static_volume:/static
    ports:
      - 17354:17354

  db:
    image: mysql:latest
    restart: always
    volumes:
      - "static_volume:/app/static"
    expose:
      - 3306
    environment:
      #MYSQL_DATABASE: "plt"
      MYSQL_USER: "beta"
      MYSQL_PASSWORD: "kawaikawai"
      MYSQL_ROOT_PASSWORD: "betaiskawaikawai"

  adminer:
    image: adminer:latest
    ports:
      - 37501:8080


  core:
    build: core
    links:
      - db
    depends_on: 
      - db
    volumes:
      - static_volume:/app/static
      - "./core/data/db.sqlite3:/app/db.sqlite3"
    expose:
      - 8000


volumes:
  static_volume: